
import type { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { name: 'Genesis', testament: 'Old', category: 'Pentateuch' },
  { name: 'Exodus', testament: 'Old', category: 'Pentateuch' },
  { name: 'Leviticus', testament: 'Old', category: 'Pentateuch' },
  { name: 'Numbers', testament: 'Old', category: 'Pentateuch' },
  { name: 'Deuteronomy', testament: 'Old', category: 'Pentateuch' },
  { name: 'Joshua', testament: 'Old', category: 'History' },
  { name: 'Judges', testament: 'Old', category: 'History' },
  { name: 'Ruth', testament: 'Old', category: 'History' },
  { name: '1 Samuel', testament: 'Old', category: 'History' },
  { name: '2 Samuel', testament: 'Old', category: 'History' },
  { name: '1 Kings', testament: 'Old', category: 'History' },
  { name: '2 Kings', testament: 'Old', category: 'History' },
  { name: '1 Chronicles', testament: 'Old', category: 'History' },
  { name: '2 Chronicles', testament: 'Old', category: 'History' },
  { name: 'Ezra', testament: 'Old', category: 'History' },
  { name: 'Nehemiah', testament: 'Old', category: 'History' },
  { name: 'Esther', testament: 'Old', category: 'History' },
  { name: 'Job', testament: 'Old', category: 'Poetry' },
  { name: 'Psalms', testament: 'Old', category: 'Poetry' },
  { name: 'Proverbs', testament: 'Old', category: 'Poetry' },
  { name: 'Ecclesiastes', testament: 'Old', category: 'Poetry' },
  { name: 'Song of Solomon', testament: 'Old', category: 'Poetry' },
  { name: 'Isaiah', testament: 'Old', category: 'Major Prophets' },
  { name: 'Jeremiah', testament: 'Old', category: 'Major Prophets' },
  { name: 'Lamentations', testament: 'Old', category: 'Major Prophets' },
  { name: 'Ezekiel', testament: 'Old', category: 'Major Prophets' },
  { name: 'Daniel', testament: 'Old', category: 'Major Prophets' },
  { name: 'Hosea', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Joel', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Amos', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Obadiah', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Jonah', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Micah', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Nahum', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Habakkuk', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Zephaniah', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Haggai', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Zechariah', testament: 'Old', category: 'Minor Prophets' },
  { name: 'Malachi', testament: 'Old', category: 'Minor Prophets' },

  // New Testament
  { name: 'Matthew', testament: 'New', category: 'Gospels' },
  { name: 'Mark', testament: 'New', category: 'Gospels' },
  { name: 'Luke', testament: 'New', category: 'Gospels' },
  { name: 'John', testament: 'New', category: 'Gospels' },
  { name: 'Acts', testament: 'New', category: 'History' },
  { name: 'Romans', testament: 'New', category: 'Pauline Epistles' },
  { name: '1 Corinthians', testament: 'New', category: 'Pauline Epistles' },
  { name: '2 Corinthians', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Galatians', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Ephesians', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Philippians', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Colossians', testament: 'New', category: 'Pauline Epistles' },
  { name: '1 Thessalonians', testament: 'New', category: 'Pauline Epistles' },
  { name: '2 Thessalonians', testament: 'New', category: 'Pauline Epistles' },
  { name: '1 Timothy', testament: 'New', category: 'Pauline Epistles' },
  { name: '2 Timothy', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Titus', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Philemon', testament: 'New', category: 'Pauline Epistles' },
  { name: 'Hebrews', testament: 'New', category: 'General Epistles' },
  { name: 'James', testament: 'New', category: 'General Epistles' },
  { name: '1 Peter', testament: 'New', category: 'General Epistles' },
  { name: '2 Peter', testament: 'New', category: 'General Epistles' },
  { name: '1 John', testament: 'New', category: 'General Epistles' },
  { name: '2 John', testament: 'New', category: 'General Epistles' },
  { name: '3 John', testament: 'New', category: 'General Epistles' },
  { name: 'Jude', testament: 'New', category: 'General Epistles' },
  { name: 'Revelation', testament: 'New', category: 'Apocalyptic' },
];

export const BOOK_CATEGORIES = [
    { name: 'Pentateuch (OT)', category: 'Pentateuch' },
    { name: 'History (OT)', category: 'History', testament: 'Old' },
    { name: 'Poetry (OT)', category: 'Poetry' },
    { name: 'Major Prophets (OT)', category: 'Major Prophets' },
    { name: 'Minor Prophets (OT)', category: 'Minor Prophets' },
    { name: 'Gospels (NT)', category: 'Gospels' },
    { name: 'History (NT)', category: 'History', testament: 'New' },
    { name: 'Pauline Epistles (NT)', category: 'Pauline Epistles' },
    { name: 'General Epistles (NT)', category: 'General Epistles' },
    { name: 'Apocalyptic (NT)', category: 'Apocalyptic' },
];
